### ISSUE TITLE
Great work!!! :) 

### ISSUE THREAD

**Issue by IhorSyerkov** [j5lien/esphome-idasen-desk-controller#1]
@j5lien You did great work. Did you think move it to official esphome components https://github.com/esphome/esphome/tree/dev/esphome/components ?

**Comment by j5lien** [comment]
Thanks !
I want to use it for a while and get more feedback before considering adding it to the main repo.

**Comment by IhorSyerkov** [comment]
I'm willing to help. Currently I develop lovelace card https://github.com/IhorSyerkov/linak-desk-card.
