### ISSUE TITLE
Incompatibility with esp32_ble_tracker

### ISSUE THREAD

**Issue by spyfly** [j5lien/esphome-idasen-desk-controller#10]
It seems like there is an incompatibility with esp32_ble_tracker, which causes theESP32 to reboot every couple minutes.

Here's the log output:
```
[23:44:39][W][esp32_ble_tracker:164]: ESP-IDF BLE scan never terminated, rebooting to restore BLE stack...
[23:44:39][I][app:132]: Forcing a reboot...
```

The only other integration I am using is [Xiaomi Mijia BLE](https://esphome.io/components/sensor/xiaomi_ble.html)

**Comment by j5lien** [comment]
It doesn't use the same bluetooth libraries so it won't be compatible I think

**Comment by spyfly** [comment]
> It doesn't use the same bluetooth libraries so it won't be compatible I think

Yeah, figured that out yesterday when looking into the codebase. I've deployed a dedicated ESP32 for the desk control to fix this issue for now.

However even if you use the same library, having a constantly active connection to the desk may also be the cause of this issue.

**Comment by j5lien** [comment]
Possible, I keep an active connection to be notified when moving the desk from the controller.

**Comment by j5lien** [comment]
It should be compatible with the new version

**Comment by spyfly** [comment]
> It should be compatible with the new version

Amazing, now I don't have to run a second ESP32, just for my desk anymore :+1:

Thanks a lot for resolving this issue :heart:
