### ISSUE TITLE
new esphome version breaks compilation

### ISSUE THREAD

**Issue by jason-glynn** [j5lien/esphome-idasen-desk-controller#55]
After installing latest esphome version, cannot update esp with idasen desk controller plugin.

needed to also include "type: characteristic" in esphome config entry for ble_client sensor.

compilation error log:
Processing esphome-bt-monitor2 (board: nodemcu-32s; framework: arduino; platform: platformio/espressif32 @ 3.5.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- AsyncTCP-esphome @ 1.2.2
|-- WiFi @ 1.0
|-- FS @ 1.0
|-- Update @ 1.0
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- AsyncTCP-esphome @ 1.2.2
|-- DNSServer @ 1.1.0
|-- ESPmDNS @ 1.0
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/esphome-bt-monitor2/src/esphome/components/api/api_connection.cpp.o
Compiling .pioenvs/esphome-bt-monitor2/src/esphome/components/api/api_pb2.cpp.o
Compiling .pioenvs/esphome-bt-monitor2/src/esphome/components/api/api_pb2_service.cpp.o
Compiling .pioenvs/esphome-bt-monitor2/src/esphome/components/api/api_server.cpp.o
Compiling .pioenvs/esphome-bt-monitor2/src/esphome/components/api/list_entities.cpp.o
Compiling .pioenvs/esphome-bt-monitor2/src/esphome/components/api/subscribe_state.cpp.o
Compiling .pioenvs/esphome-bt-monitor2/src/esphome/components/api/user_services.cpp.o
Compiling .pioenvs/esphome-bt-monitor2/src/esphome/components/ble_client/automation.cpp.o
Compiling .pioenvs/esphome-bt-monitor2/src/esphome/components/ble_client/ble_client.cpp.o
Compiling .pioenvs/esphome-bt-monitor2/src/esphome/components/ble_client/sensor/ble_rssi_sensor.cpp.o
Compiling .pioenvs/esphome-bt-monitor2/src/esphome/components/ble_client/sensor/ble_sensor.cpp.o
Compiling .pioenvs/esphome-bt-monitor2/src/esphome/components/captive_portal/captive_portal.cpp.o
Compiling .pioenvs/esphome-bt-monitor2/src/esphome/components/esp32_ble_client/ble_characteristic.cpp.o
Compiling .pioenvs/esphome-bt-monitor2/src/esphome/components/esp32_ble_client/ble_client_base.cpp.o
Compiling .pioenvs/esphome-bt-monitor2/src/esphome/components/esp32_ble_client/ble_service.cpp.o
Compiling .pioenvs/esphome-bt-monitor2/src/esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp.o
Compiling .pioenvs/esphome-bt-monitor2/src/esphome/components/homeassistant/time/homeassistant_time.cpp.o
Compiling .pioenvs/esphome-bt-monitor2/src/esphome/components/idasen_desk_controller/idasen_desk_controller.cpp.o
Compiling .pioenvs/esphome-bt-monitor2/src/esphome/components/logger/logger.cpp.o
Compiling .pioenvs/esphome-bt-monitor2/src/esphome/components/md5/md5.cpp.o
Compiling .pioenvs/esphome-bt-monitor2/src/esphome/components/mdns/mdns_component.cpp.o
src/esphome/components/idasen_desk_controller/idasen_desk_controller.cpp: In member function 'virtual void esphome::idasen_desk_controller::IdasenDeskControllerComponent::gattc_event_handler(esp_gattc_cb_event_t, esp_gatt_if_t, esp_ble_gattc_cb_param_t*)':
src/esphome/components/idasen_desk_controller/idasen_desk_controller.cpp:68:61: error: 'class esphome::ble_client::BLEClient' has no member named 'gattc_if'
           esp_ble_gattc_register_for_notify(this->parent()->gattc_if, this->parent()->remote_bda, this->output_handle_);
                                                             ^
src/esphome/components/idasen_desk_controller/idasen_desk_controller.cpp:68:87: error: 'class esphome::ble_client::BLEClient' has no member named 'remote_bda'
           esp_ble_gattc_register_for_notify(this->parent()->gattc_if, this->parent()->remote_bda, this->output_handle_);
                                                                                       ^
src/esphome/components/idasen_desk_controller/idasen_desk_controller.cpp:101:50: error: 'class esphome::ble_client::BLEClient' has no member named 'conn_id'
       if (param->read.conn_id != this->parent()->conn_id)
                                                  ^
src/esphome/components/idasen_desk_controller/idasen_desk_controller.cpp:115:52: error: 'class esphome::ble_client::BLEClient' has no member named 'conn_id'
       if (param->notify.conn_id != this->parent()->conn_id || param->notify.handle != this->output_handle_)
                                                    ^
src/esphome/components/idasen_desk_controller/idasen_desk_controller.cpp: In member function 'void esphome::idasen_desk_controller::IdasenDeskControllerComponent::write_value_(uint16_t, short unsigned int)':
src/esphome/components/idasen_desk_controller/idasen_desk_controller.cpp:141:65: error: 'class esphome::ble_client::BLEClient' has no member named 'gattc_if'
   esp_err_t status = ::esp_ble_gattc_write_char(this->parent()->gattc_if, this->parent()->conn_id, handle, 2, data,
                                                                 ^
src/esphome/components/idasen_desk_controller/idasen_desk_controller.cpp:141:91: error: 'class esphome::ble_client::BLEClient' has no member named 'conn_id'
   esp_err_t status = ::esp_ble_gattc_write_char(this->parent()->gattc_if, this->parent()->conn_id, handle, 2, data,
                                                                                           ^
src/esphome/components/idasen_desk_controller/idasen_desk_controller.cpp: In member function 'void esphome::idasen_desk_controller::IdasenDeskControllerComponent::read_value_(uint16_t)':
src/esphome/components/idasen_desk_controller/idasen_desk_controller.cpp:152:47: error: 'class esphome::ble_client::BLEClient' has no member named 'gattc_if'
       esp_ble_gattc_read_char(this->parent()->gattc_if, this->parent()->conn_id, handle, ESP_GATT_AUTH_REQ_NONE);
                                               ^
src/esphome/components/idasen_desk_controller/idasen_desk_controller.cpp:152:73: error: 'class esphome::ble_client::BLEClient' has no member named 'conn_id'
       esp_ble_gattc_read_char(this->parent()->gattc_if, this->parent()->conn_id, handle, ESP_GATT_AUTH_REQ_NONE);
                                                                         ^
*** [.pioenvs/esphome-bt-monitor2/src/esphome/components/idasen_desk_controller/idasen_desk_controller.cpp.o] Error 1
========================= [FAILED] Took 261.46 seconds =========================

**Comment by lucasartoni** [comment]
yep, same thing here

**Comment by j5lien** [comment]
The fix has been merged!
