### ISSUE TITLE
Update compatibility

### ISSUE THREAD

**Issue by mmicire** [j5lien/esphome-idasen-desk-controller#57]
Not an issue, but you can add the BEKANT desk to your compatibility list.  Works perfectly with that desk base.  https://www.ikea.com/au/en/p/bekant-underframe-sit-stand-f-table-tp-el-black-20325885/ 

Thank you for the recent update.  I've been waiting to try this out since things broke.

**Comment by mmicire** [comment]
Apologies.  The desk that I have working is the IDÅSEN, not the BEKANT, as mentioned prior.
https://www.ikea.com/au/en/p/idasen-underframe-sit-stand-f-table-tp-el-dark-grey-50412169/

**Comment by nilsi** [comment]
So is it not possible to use this with Bekant in the first link? Does anyone know?

Edit: I guess not since Bekant doesn't have Bluetooth
